require 'sample/university'
require 'sample/career'
require 'sample/high_school'
require 'sample/location'
require 'sample/personality'
require 'sample/personality_category'
require 'sample/personality_major'
require 'sample/trey_visay'
